apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tappoc
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
  name: tappoc
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
      - name: BP_MAVEN_BUILT_MODULE
        value: webapp
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-pl webapp -am package"
  params:
    - name: buildServiceBindings
      value:
        - kind: Secret
          name: bucketrepo-settings-xml