apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tappoc
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
  name: tappoc
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
      - name: BP_MAVEN_BUILT_MODULE
        value: webapp
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-pl webapp -am package -DskipTests"
  env:
    - name: JAVA_TOOL_OPTIONS
      value: -Dmanagement.health.probes.enabled='false'
  params:
    - name: buildServiceBindings
      value:
        - kind: Secret
          name: bucketrepo-settings-xml
    - name: api_descriptor
      value:
        description: DemoApp
        location:
          path: /v3/api-docs
        owner: demo
        system: dev
        type: openapi
  serviceClaims:
    - name: wavefront
      ref:
        apiVersion: v1
        kind: Secret
        name: production-wavefront
    - name: postgres
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: postgres-bs-test